### ISSUE TITLE
keyed benchmark?

### ISSUE THREAD

**Issue by leeoniya** [thysultan/dio.js#10]
hey @thysultan 

was wondering if you were planning on submitting a keyed v6 or v7 implementation of js-framework-benchmark. curious how it would perform :)

**Comment by thysultan** [comment]
Yes, once 7.0 is ready.

**Comment by lukeed** [comment]
Curious too 😃 Haven't been able to benchmark anything since 4.x. Curious how all these new features impact performance, esp compared to 3.x.

Good work!

**Comment by thysultan** [comment]
Yeah i'm also curious to see how it performs, haven't run js-framework-benchmark since 4.0

**Comment by thysultan** [comment]
Given the new features i'd say it's pretty good - (https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html)[https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html]. slightly slower than 3.X
