### ISSUE TITLE
Why not making it compatible with React.js?

### ISSUE THREAD

**Issue by rosenfeld** [thysultan/dio.js#16]
Hi, I find it interesting that I can use the same code with React, Preact and Inferno by simply importing the equivalent `h`, `render` and `Component` from them. I'd love to be able to do the same with Dio.js, but it seems Dio's API is not compatible. For example, inside a component's `render` I'd have access to the props with `this.this.props` instead of `this.props`. Wouldn't you be interested in keeping the same compatibility layer in the basic API, just like Preact and Inferno do? This way, authors of React-like application can easily switch their VDOM implementation and compare them.

**Comment by thysultan** [comment]
I don't understand, where does `this.this.props` come from? It should work with `this.props`, in fact `this.this.props` is not an API of dio.

**Comment by rosenfeld** [comment]
I have some common file that exports `h`, `render` and `Component` and it currently requires one of React, Inferno or Preact and the application works exactly the same way (except in some cases when using third-party components for Preact since it compares to the actual DOM). I tried to add Dio.js as an option and exported dio.h, dio.render and dio.Component. However, `this.props` returns an empty object inside `render()` while I was expecting to get the props passed to the component. They are available through `this.this.props` though.

**Comment by rosenfeld** [comment]
We use JSX, which calls `dio.h` for rendering the component.

**Comment by rosenfeld** [comment]
And I installed it using `yarn add dio.js --dev` and the wrapper file required through webpack is like follows:

``` javascript
import { h, render, Component } from 'dio.js'
export { h, render, Component }
```

**Comment by thysultan** [comment]
`this.this.props`is not a dio API. 

Can you post a reproduction of the issue because if this works in preact and not in dio then it must be a bug since dio has a 1-1 api surface with dio(with the only exception being context)

**Comment by rosenfeld** [comment]
I'm having a hard time trying to create an example application here:

https://codesandbox.io/s/R6m9xVpZw

It seems to work at first but then any changes to the code and it will only work when I press the refresh button in the right pane. The problem is probably not that simple to reproduce because it seems to work in codesandbox.io...

**Comment by thysultan** [comment]
Could this be a problem with codesandbox instead of dio?

**Comment by rosenfeld** [comment]
No, the original problem happens locally, I'm just trying to replicate it in codesandbox.io but I couldn't so far. It doesn't seem like it's easy to reproduce it...

**Comment by thysultan** [comment]
You you post the original problem as is in a codesandbox/jsfiddle/github repo

**Comment by rosenfeld** [comment]
Here you are. It's still work in progress but you can see the problem:

https://codesandbox.io/s/R6m9xVpZw

**Comment by rosenfeld** [comment]
If you replace dio with preact you'll notice that it works with Preact (or Inferno or React)

**Comment by rosenfeld** [comment]
With Preact there are other problems, like the input element being remounted when some item's checkbox is checked, closing the dropdown menu. This doesn't happen with Inferno or React for example...

**Comment by rosenfeld** [comment]
Sorry, I forgot to save the other file before sharing the link. It should be working now.

**Comment by rosenfeld** [comment]
Could you reproduce the issue?

**Comment by thysultan** [comment]
Yes.

**Comment by rosenfeld** [comment]
great :)

**Comment by thysultan** [comment]
Does this work in React?

**Comment by thysultan** [comment]
Specifically this part, `super()` not passing props.

**Comment by rosenfeld** [comment]
Yes, it works in React too

**Comment by rosenfeld** [comment]
https://stackoverflow.com/questions/30571875/whats-the-difference-between-super-and-superprops-in-react-when-using-e

**Comment by thysultan** [comment]
Thanks, then that is probably the problem. Will push a patch for this in a bit.

**Comment by rosenfeld** [comment]
Awesome, thanks. At least I know I only have to pass props to super to make it work with Dio for now :)

**Comment by rosenfeld** [comment]
This doesn't seem to be the only problem though. If you look at the example, you should see the checkboxes in the dropdown menu for the first input both with Preact, Inferno and React. However it doesn't show the checkboxes with Dio for some reason...

**Comment by thysultan** [comment]
Can you point me to the code for the dropdown menu content?

**Comment by rosenfeld** [comment]
The code is in the file "autocomplete.js", not in "main.js". I'm simulating using third-party components with React, Preact, Inferno and Dio and see how they behave... Check the function doAddMenuItems

**Comment by thysultan** [comment]
Where does the callstack start in main.js?

**Comment by rosenfeld** [comment]
The application is rendered by renderTree(). In `Autocomplete.render` I get a reference to the input. I lazily initialize the input when it gets focus. That will trigger the code in `autocomplete.js`. There are some global event handlers registered by `autocomplete.js` that should respond to events. Pressing the down arrow, typing or clicking on the down button should trigger the `openAutocomplete` which should create the suggestions box. That should call the `addMenuItems` which should call `doAddMenuItems`.

**Comment by rosenfeld** [comment]
It's still work-in-progress, it's not yet complete, so it may not make much sense to you. I have to render a thousand of autocomplete fields and it's important for me to be able to lazily load them and use little memory. This is an experiment trying to achieve that. There's much more to do, like handling the case with thousands of options in the menu by only rendering the visible ones and some other tricks...

**Comment by thysultan** [comment]
Does any of this rely on something coming from main.js?

**Comment by thysultan** [comment]
Specifically the view library, i.e refs/events

**Comment by rosenfeld** [comment]
Yes, the dataSource property passed to the constructor in the focus event handler. It uses a `dataset` function to set some unique property name in the input with the dataSource.

**Comment by rosenfeld** [comment]
But this part should be working fine as the options are showed correctly. I just don't understand why the checkbox is not being added (or maybe it's being removed by Dio).

**Comment by rosenfeld** [comment]
The problem is not likely to be caused by the code in  `main.js`. It's probably caused by how Dio interacts with the third-party library, which touches the DOM directly.

**Comment by rosenfeld** [comment]
Does Dio compare against the actual DOM or against the previous VDOM when diffing?

**Comment by thysultan** [comment]
Do you know where is this handshake being made?

>or maybe it's being removed by Dio

I don't think this is the issue since dio doesn't touch the DOM when diff'ng.

>It's probably caused by how Dio interacts with the third-party library, which touches the DOM directly.

Probably, i'm trying to find where exactly this is happening since DIO doesn't rely on the state of the DOM when diff'ing.

**Comment by rosenfeld** [comment]
Whenever the menu is opened it's recreated. A div element will hold the options. It's created in openAutocomplete. Then it's populated by addMenuItems. The checkboxes should be created when there's a "data-multiple" attribute associated with the input. Maybe it isn't being added by Dio?

**Comment by rosenfeld** [comment]
Ok, I guess this is the issue

**Comment by rosenfeld** [comment]
It adds an empty "data-multiple" attribute when it should have some value. At least this is how the other libraries handle it when you pass {true} to it...

**Comment by thysultan** [comment]
line of code?

**Comment by rosenfeld** [comment]
Changing to this in main.js fixed it for me:

```
        data-multiple={ this.props.multiple ? 'true' : false } data-key-based={ this.props.keyBased }
```

**Comment by rosenfeld** [comment]
it was `data-multiple={ this.props.multiple }`

**Comment by thysultan** [comment]
Ok, will try to recreate a small test case with this.

**Comment by rosenfeld** [comment]
Thanks

**Comment by thysultan** [comment]
Yes that seems to be the case, Fixed it, should push a patch with both these issues in a bit.

**Comment by rosenfeld** [comment]
thanks!

**Comment by rosenfeld** [comment]
Actually it shouldn't return false but undefined or null I guess: `data-multiple={ this.props.multiple && 'true' }` is a proper fix for making it work with Dio as expected so far.

**Comment by thysultan** [comment]
Thanks for finding this, Patched in 7.0.4.

For the most part dio's public API semantics was made to resemble preact/react.

**Comment by rosenfeld** [comment]
Thank you, it's awesome to have so many options when designing react-like applications :)

**Comment by rosenfeld** [comment]
I'm still curious. Does your reconciler compares against the real DOM, like Preact, or against the previous tree like React and Inferno?

**Comment by thysultan** [comment]
Against the previous tree.

**Comment by thysultan** [comment]
There's also a few subtle extra features when compared to React/Preact/Inferno, to name a few.

1. DIO calls events and refs within the context of their root component, Which means you don't need to `.bind` events/refs.

2. Supports returning state from events/lifecycle/refs methods.

3. Supports passing Promises to `setState` and returning Promises from render which allows DIO to pause/resume updates similar to Fiber.

4. Supports returning a Promise from `componentWillUnmount` to await for animations to end before un-mounting and passes the corresponding DOM node to `componentWillUnmount` and `componentWillMount` as an argument to make this easier.
