### ISSUE TITLE
'Github' typos

### ISSUE THREAD

**Issue by 0joshuaolson1** [thysultan/dio.js#17]
https://github.com/thysultan/dio.js/blob/786f2dbac6fee35db60741d405da841ad9f20237/docs/examples.html#L22
https://github.com/thysultan/dio.js/blob/b1783101f9d2e5b43dfbe589719665e84f620de3/docs/api.html#L22
https://github.com/thysultan/dio.js/blob/205b08a7eb0b4b52ab68367cba5173944d17716b/docs/index.html#L22
https://github.com/thysultan/dio.js/blob/b1783101f9d2e5b43dfbe589719665e84f620de3/docs/examples/particles.html#L26
https://github.com/thysultan/dio.js/blob/b1783101f9d2e5b43dfbe589719665e84f620de3/docs/examples/5k.html#L25
https://github.com/thysultan/dio.js/blob/eef5a5d04054e76dbef6ed938ee8eeae12f63461/docs/introduction.html#L22
https://github.com/thysultan/dio.js/blob/eef5a5d04054e76dbef6ed938ee8eeae12f63461/docs/introduction.html#L372

**Comment by thysultan** [comment]
The uppercase `G` int `github` is intentional, is that what you meant?

**Comment by 0joshuaolson1** [comment]
The 'h' should be 'H'.

**Comment by thysultan** [comment]
The lowercase `h` is intentional.

**Comment by 0joshuaolson1** [comment]
Github -> GitHub

**Comment by thysultan** [comment]
Yes, the current version `Github` is intentional.

**Comment by 0joshuaolson1** [comment]
And a typo. At the bottom of this page is (C) 2017 GitHub, Inc.

**Comment by thysultan** [comment]
Can you submit a PR for this?

**Comment by 0joshuaolson1** [comment]
Okay.
