### ISSUE TITLE
undefined rendered as space

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#19]
https://github.com/thysultan/dio.js/blob/master/src/Render.js#L13

I believe this should be an empty string instead `''`

edit:
https://github.com/thysultan/dio.js/blob/fe06a9918162b355b5aae82b0fd2bb3492e9fed5/src/Element.js#L173
https://github.com/thysultan/dio.js/blob/fe06a9918162b355b5aae82b0fd2bb3492e9fed5/src/Element.js#L296

**Comment by thysultan** [comment]
Yes, this should be an empty string.
