### ISSUE TITLE
attrs is dead code

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#20]
I can't seem to find where a node's `attrs` property is either set or used
Also the test for it is bugged
https://github.com/thysultan/dio.js/blob/70dbe849b701d484373fd10d1733157fe661f53d/tests/Element.spec.js#L16 `props instanceof Object`

**Comment by thysultan** [comment]
Yes, the tests need some work, the code is in `Element.js#50-90`. If you're up for it i can walk you through what's where. I'm currently working on V8 on [https://github.com/thysultan/dio.js/tree/V8](https://github.com/thysultan/dio.js/tree/V8) it's almost done but i could use some help.

**Comment by Zolmeister** [comment]
reading https://github.com/thysultan/dio.js/blob/70dbe849b701d484373fd10d1733157fe661f53d/src/Attribute.js in v8 now makes sense
