### ISSUE TITLE
broken lifecycle behavior for function components

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#21]
for function components, only one of didMount or willMount is ever called, depending on which was defined last

```js
function render() {
  return h('div')
}
```
```js
render.componentDidMount = function() { console.log('did mount') }
render.componentWillMount = function() { console.log('will mount') }
// 'will mount'
```
```js
render.componentWillMount = function() { console.log('will mount') }
render.componentDidMount = function() { console.log('did mount') }
// 'did mount'
```

expected
```js
// 'will mount'
// 'did mount'
```

possibly related, this is dead code
https://github.com/thysultan/dio.js/blob/70dbe849b701d484373fd10d1733157fe661f53d/src/Boundary.js#L78

**Comment by thysultan** [comment]
Can't reproduce this – [https://jsbin.com/nelusofoyi/edit?html,js,output](https://jsbin.com/nelusofoyi/edit?html,js,output).

>possibly related, this is dead code

`componentWillUnmount` supports a promise return type for unmount animations for example [https://dio.js.org/api.html#animations](https://dio.js.org/api.html#animations)

**Comment by Zolmeister** [comment]
sorry, I was returning the mount function as the render function
