### ISSUE TITLE
Render errors should serialize to an empty string

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#23]
```js
class Component {
  render() {
    throw new Error('x')
  }
}
console.log(`${h(Component)}`)
// expected
''
// got
`<pre>{
  &quot;location&quot;: &quot;render&quot;,
  &quot;message&quot;: {}
}</pre>`
```

**Comment by Zolmeister** [comment]
sorry, reading the docs it makes sense.
it's converting the error to a node, because it's expecting a node

**Comment by thysultan** [comment]
Actually strings, are valid nodes returned from render/componentDidCatch, it's that err in this case is an object, and it uses JSON.stringfiy on unknown objects.
