### ISSUE TITLE
access DOM node in event callback

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#24]
currently events are called with `owner` as `this` instead of the DOM node

I'd prefer unwrapped event callbacks, but if that's a deal-breaker passing the DOM node to the event handler is a reasonable alternative

e.g.
```javascript
render = function() {
  h('a', {
    href: '/local'
    onclick: function(e) { router.go this.href }
    onclick: function(e, $$el) { router.go $$el.href } // alternate
  })
}
```

**Comment by thysultan** [comment]
The event is executed in the `owner` component context to help avoid binding function to `this`. However `e.target` does point to the element.

**Comment by Zolmeister** [comment]
`e.target` doesn't work (https://stackoverflow.com/questions/12077859/difference-between-this-and-event-target/21667010#21667010)
but (just learned) `e.currentTarget` does
