### ISSUE TITLE
full page diff

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#25]
The server side rendering example includes the entire page DOM
https://dio.js.org/api.html#server

However it is not possible to render to the document object.
What is the expected way to diff the `<head>` block?

the major use case is the `<title>` tag, but also having a dynamic [manifest.json](https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/) for marketplaces (e.g. [clay.io](https://clay.io) (mobile))

**Comment by thysultan** [comment]
What do you mean it by 

>However it is not possible to render to the document object.

You can render to `document.documentElement` the `<html>` element or any element within the document, including head.

**Comment by Zolmeister** [comment]
trying to render to `document.documentElement` fails because it creates a child instead of replacing

```js
render($app, document.documentElement)
```
```html
<html>
  <html></html>
</html>
```

and I haven't been able to get the `hydrate` method to work either

```js
render($app, null, document.documentElement)
// error Cannot read property 'flag' of undefined
```
(https://github.com/thysultan/dio.js/blob/master/src/Hydrate.js#L46)
