### ISSUE TITLE
[v8] [question] Partial <head> diff support?

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#30]
Problem:
Third party libraries tend to like adding resources dynamically to `<head>` at run-time. Additionally, currently the initial diff re-writes resource tags causing re-requesting (e.g. `<script src="xxx">`)

Original Solution:
I wrote a custom diff for `<head>` which only diffed `<link>`, `<meta>` and `<title>` tags

Proposed Solution:
blank fragment placeholder, allow appending to DOM node

e.g.
```
<head>
  <title>xxx</title>
  h(BLANK_FRAGMENT)
```
then a library could append to `<head>` without altering diffing

I have no clue whether this makes sense. Another Idea I had was to mark original DOM nodes as `editable` (all new dio nodes would also be marked), then diff would ignore non-`editable` DOM nodes. (this doesn't fix re-requesting on initial diff)

**Comment by thysultan** [comment]
This could be where a `.hydrate` API would come into play.

**Comment by Zolmeister** [comment]
`hydrate` would fix re-requesting, but not `<style>` appends to `<head>`

**Comment by thysultan** [comment]
> but not <style> appends to <head>

Elaborate.

**Comment by Zolmeister** [comment]
When using webpack [style-loader](https://github.com/webpack-contrib/style-loader) (with hot module replacement), it injects css in `<head>` as a `<style>` tag.

When using [woofmark](https://github.com/bevacqua/woofmark) to prompt users for an image, the modal DOM is appended to `<body>`.

[Google Charts](https://developers.google.com/chart/interactive/docs/quick_start) also dynamically appends `<link>` tags to the document `<head>`

**Comment by thysultan** [comment]
How would hydration not apply to those. The heuristics of hydration would look for the start node, if it does not exist it will append to the container.

**Comment by Zolmeister** [comment]
Perhaps I misunderstand the mechanics of hydration. I thought it build a vdom from the existing DOM for the initial diff. The `<style>` tag injection happens at run-time, and would be diffed away at the next render cycle (or would it simply ignore any DOM nodes not part of the initial tree?).

**Comment by thysultan** [comment]
It instantiates the the vdom independent of the DOM, and hydrates the exist DOM nodes that match to this instance, the source of truth is still the vdom.

**Comment by thysultan** [comment]
That said the mechanics of hydration have not yet been implemented, but i think this should handle a wide vary of cases like this.

**Comment by Zolmeister** [comment]
'twas my fault, but fixing it has lead to great progress! :chart_with_upwards_trend:
