### ISSUE TITLE
setState and state doesn't work

### ISSUE THREAD

**Issue by danfma** [thysultan/dio.js#31]
Hey, guys!

Nice work in this library!! But, I had played with it a little and I found a bug.

## LIBRARY VERSION

7.1.0

## PROBLEM

The `state` and `setState` aren't in sync.

## EXPECTED

* When the `setState` is called, it should update the state property and trigger the rendering again, if there are changes.

## CURRENT BEHAVIOR

* No matter how do you set the `state` using the `setState`, it will always contain an empty object as the `state`.

**Comment by Zolmeister** [comment]
might want to check out `V8` branch

**Comment by danfma** [comment]
Ok, I'll try here.

**Comment by thysultan** [comment]
This should work with 8.0.0
