### ISSUE TITLE
[V8] Webpack Hot Module Replacement Support

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#33]
Webpack [hot module replacement](https://webpack.js.org/concepts/hot-module-replacement/) is a fantastic tool for web development (which I utilize extensively).

I've been attempting to get dio to support it but have been unsuccessful so far.
If you have the time I'd be grateful if you gave it a shot.

I've created the following repository for experimentation:
https://github.com/Zolmeister/dio-hmr

**Comment by thysultan** [comment]
Came across Dan's post on this [hot-reloading-in-react](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf) that might be a good starting point of how this works in React-hot-loader.

**Comment by Zolmeister** [comment]
React-Hot-Loader is insane. It's perfectly acceptable if the entire app has to be re-rendered. (https://github.com/thysultan/dio.js/pull/28#issuecomment-330079225)

**Comment by Zolmeister** [comment]
https://github.com/Zolmeister/dio-hmr/commit/e3538e9dc31e5ca18dbf1d2f201f29006f9dbbad
