### ISSUE TITLE
[V8] ~100% test coverage

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#34]
How to add code coverage with [istanbul](https://github.com/istanbuljs/nyc):

```bash
npm i -D nyc
# npm i -D graceful-readlink
```

```js
// package.json > "scripts"
"test": "nyc --reporter=lcov --reporter=text mocha --require script/test/index.js"
```

now when `test` is run, code coverage will print to console, with a detailed report available at
```
/coverage/lcov-report/index.html
```

e.g. `getDefaultProps()` is never hit by tests

**Comment by thysultan** [comment]
Thanks, added, this would help clear up what test should be left to write to reach ~100%. It's currently at ~90%.
