### ISSUE TITLE
Consistent function naming, dio.curry

### ISSUE THREAD

**Issue by yosbelms** [thysultan/dio.js#4]
A curried function is a function that can be partialy applied and executes once the number of provided arguments is equal to the function arity, example:
```js
var curried = curry(function(a, b, c){
    console.log(a + b + c)
}) 

curried(1)(2)(3)
curried(1, 2)(3)
curried(1)(2, 3)
// the three calls logs 6
```

AFAIK `dio.curry` does not returns a curried function, it returns a function wrapped with fixed predefined arguments. To avoid confusion the renaming should be taken in consideration. My proposal is:

- dio.defer
- dio.wrap
- dio.listener
- dio.partial

I prefer ~~`dio.defer`~~ `dio.partial`

**Comment by thysultan** [comment]
You're right it works more like `.bind` than it does currying. There's a 3.0 release soon so will add this update in there.

**Comment by thysultan** [comment]
v3.0 is released here is the [change log](https://github.com/thysultan/dio.js/blob/master/CHANGELOG.md) thanks for the suggestions, preferred defer since it sounded the most descriptive, i.e defer this function with these arguments to run when this event is triggered.

**Comment by yosbelms** [comment]
Good, since dio.js v3 addresses this issue I'm going to close this
