### ISSUE TITLE
Consider supporting mixed case events.

### ISSUE THREAD

**Issue by robdodson** [thysultan/dio.js#44]
I wanted to open this issue so folks using DIO know about it. There are a few similar bugs in other libraries.

> DIO can listen to native DOM events dispatched from Custom Elements. However, it uses a heuristic to convert JSX event binding syntax into event names, and always lowercases the events. For example onFooUpdated={handleFoo} tells DIO to listen for an event called 'fooupdated'. This means DIO can support events with lowercase and kebab-case names, but not camelCase, PascalCase, or CAPScase events (e.g. 'URLchanged').
From https://custom-elements-everywhere.com/#dio-handling-events

Preact tracking bug - https://github.com/developit/preact/pull/788
Polymer tracking bug - https://github.com/Polymer/polymer/issues/4888
Stencil tracking bug - https://github.com/ionic-team/stencil/issues/373

Feel free to close if you don't think this is an actual issue or you don't intend to work on it. The main objective of my tests is just to outline what will and won't work so developers can figure out best practices.

**Comment by thysultan** [comment]
Thanks, even though the default DOM renderer doesn't support this, this was one of the considerations i had with the move to allow more control over the heuristics involved in the props namespace so that a custom renderer would be able to implement and support this if it wanted to.
