### ISSUE TITLE
Revert server-side will-mount

### ISSUE THREAD

**Issue by Zolmeister** [thysultan/dio.js#48]
This is a breaking change (semver), and seems incorrect
https://github.com/thysultan/dio.js/commit/123dd80b124e872c04d30808885d0880eacf3cc5#r26955261

> This seems wrong? Mounting is the act of DOM insertion, and should definitely never be called server-side

**Comment by thysultan** [comment]
The patch is motivated by how React handles [componentWillMount](https://reactjs.org/docs/react-component.html#componentwillmount) on the server so i think the previous behavior could be considered a bug.

Does this patch break any of your components?

**Comment by Zolmeister** [comment]
I guess for React compatibility it's reasonable (https://github.com/facebook/react/issues/7671).
And given it doesn't break my components I'm not strongly opposed to the change.

I still hold that the React api in this case is poorly designed.
