### ISSUE TITLE
Text inside muicss Button is duplicated

### ISSUE THREAD

**Issue by rosenfeld** [thysultan/dio.js#49]
Hi, I'm sorry but I can't find any online sandbox supporting aliases to provide you a link so that you could easily test it.

Basically, with webpack, one can add aliases, which can be quite useful when trying React libraries with React-compatible alternative libraries such as Dio.js, Inferno.js, Preact and NervJS. If you create aliases for both 'react$' and 'react-dom$' pointing to 'dio.js', then you should be able to run this example from the MUI-React documentation:

https://www.muicss.com/docs/v1/react/introduction

Just include the CSS as explained in the introduction and run their full example. It mostly works, but the button text is duplicated for some reason. It works fine with both React (of course) and inferno-compat aliases, so it's probably some tricky bug in Dio.js. I'd appreciate if you could figure out what's causing this behavior and fix it. I'd love to use Dio.js in my project, as it's more lightweight than Inferno.js and I also enjoy having more than one option regarding React alternatives. I tried Material UI before MUI, but not only Material UI is big but it also makes explicit use of the synthetic events API which are not supported by Dio.js (Inferno does support them, so it works with inferno-compat, but if I were able to use MUI with Dio.js, that would be very helpful).

I hope you have some time and interest in making it easy for Dio.js users to use existing React UI libraries through aliases in their webpack projects :)

Thanks for Dio.js :)

**Comment by rosenfeld** [comment]
Hmm, that makes sense. On that case, which one is used by React and Inferno, do you know?

Regarding Material UI, I remember I added an AppBar using the first example here:

http://www.material-ui.com/#/components/app-bar

When clicking on the menu icon I'd see some errors logged in the console. If I remember correctly, Material UI would call something like event.persist() which seems to be added by both React and inferno-compat to support synthetic events:

https://reactjs.org/docs/events.html

I'm not sure if Inferno actually supports synthetic events, but at least it adds the `persist` method to the event somehow.

**Comment by thysultan** [comment]
>Hmm, that makes sense. On that case, which one is used by React and Inferno, do you know?

React prefers(one replaces the other) children elements to children props, DIO in this case was accumulating both. I have a fix for this in the next patch.

**Comment by rosenfeld** [comment]
Oh, great :) Please let me know once it's released :)

**Comment by thysultan** [comment]
This is patched in [8.2.3](https://github.com/thysultan/dio.js/releases/tag/8.2.3)

**Comment by rosenfeld** [comment]
Awesome! Thanks :)

**Comment by rosenfeld** [comment]
I could confirm it worked, thank you :)

**Comment by rosenfeld** [comment]
By the way, Dio.js was mentioned in my latest article ;) https://rosenfeld.herokuapp.com/en/articles/front-end/2018-01-25-the-missing-bit-in-the-react-community-a-common-interface
