### ISSUE TITLE
How about automatic reporting errors?

### ISSUE THREAD

**Issue by rosenfeld** [thysultan/dio.js#50]
If I understood the errors handling section of the React documentation correctly it does not catch errors from event listeners. However, it seems Dio.js does catch those errors in order to display a proper stacktrace in the console logs, which is awesome, but it ends up swallowing the error, making it impossible to install a catch-all error to report them to some service such as Bugsnag, for example.

Dio.js should either allow us to provide an option to rethrow the exception after logging it, or to install a generic error handler or to add some hook in the component such as componentEventHandlerDidThrow or something like that.

What do you suggest as an approach to report such errors (since componentDidCatch is not called in those situations) to some errors monitoring service?

**Comment by thysultan** [comment]
>install a catch-all error to report them to some service such as Bugsnag

Do you have an example?

**Comment by rosenfeld** [comment]
Services such as Bugsnag would usually install themselves to either override `window.onerror` or adding the equivalent event listener in order to report them. Since you catch those errors in Dio.js the global error event is never triggered, making it impossible to report those errors with a global handler. For errors in `render()` itself and similar we may override componentDidCatch in order to manually notify the error to the service provider, but currently there's no way to report errors swallowed by Dio.js when handling errors in event handlers, like in code like this:

```javascript
render() {
  return <button onClick={()=> inexistingFunction() }>Throw error</button>
}
```

**Comment by thysultan** [comment]
I think it might be safe to re-throw event origin errors after we have obtained the relevant stack trace.

Without this restriction we might end up with the related case of [https://github.com/facebook/react/issues/10474](https://github.com/facebook/react/issues/10474) happening.

Which is the desired behavior we might want for events but not other component errors.

The other option would be to enable events as catchable errors, related discussion: [https://github.com/facebook/react/issues/11409](https://github.com/facebook/react/issues/11409)

**Comment by rosenfeld** [comment]
I like the idea of replacing the library implementing the React specs without having to change my code as long as it remains compatible with React. Having said this, until React itself decides that event handlers errors should be catchable as well, I don't think it would be really a good option for Dio.js, since I'd expect Dio.js to follow React specs as close as possible.

I didn't test the behavior in React itself but I suspect it doesn't swallow those errors like Dio.js does, right? That's why I'm reporting this in the first place. Maybe Dio.js should re-throw the original error except when already catched by componentDidCatch. If it doesn't work this way already in React I suspect it's a React bug rather than a decision from the React's team. Is it too hard to skip re-throwing when the error has been already catched by componentDidCatch?

**Comment by thysultan** [comment]
Yes, i think React re-throws for either case. We could include this into the work that is going into [https://github.com/thysultan/dio.js/issues/51](https://github.com/thysultan/dio.js/issues/51).. that said i don't think re-throwing events errors would be a problem implementation wise.

**Comment by thysultan** [comment]
I think we can also re-throw errors that are not caught by an ErrorBoundary to be more inline with try...catch and React semantics.

**Comment by rosenfeld** [comment]
Yes, that makes sense to me

**Comment by thysultan** [comment]
This will be possible once [9.0.0](https://github.com/thysultan/dio.js/pull/52) lands.

**Comment by rosenfeld** [comment]
That's awesome, thanks!
