### ISSUE TITLE
Are there any plans to support the React Context (Provider/Consumer) API?

### ISSUE THREAD

**Issue by rosenfeld** [thysultan/dio.js#54]

**Comment by thysultan** [comment]
Yes, it exists in the 9.0.0 branch/pull request.

**Comment by rosenfeld** [comment]
Oh, good to know. Any reasons why it wasn't released yet?

**Comment by thysultan** [comment]
I'm improving the public `createFactory` api used to create native reconcilers.

**Comment by rosenfeld** [comment]
Ah, okay. Would you mind commenting here once 9.0.0 is released? Or is there any other way I could get such notification?

**Comment by thysultan** [comment]
Sure, you could also subscribe to the open pull request https://github.com/thysultan/dio.js/pull/52

**Comment by rosenfeld** [comment]
Awesome, wasn't aware of it. Don't mind commenting here then, I'm already subscribed there :)
