### ISSUE TITLE
Are there any plans to support defaultValue in form elements?

### ISSUE THREAD

**Issue by rosenfeld** [thysultan/dio.js#56]
React supports the defaultValue option for several form elements, which is often used with uncontrolled components: https://reactjs.org/docs/uncontrolled-components.html

Is Dio.js going to support those as well?

**Comment by thysultan** [comment]
It should already support all native DOM attributes including `defaultValue`, did come across a bug?

**Comment by rosenfeld** [comment]
defaultValue is not a native "select" attribute, but React supports that attribute for select elements as well.

**Comment by thysultan** [comment]
Does this apply to `checkbox` and `radio` inputs – or rather what inputs does React special case `defaultValue`?

**Comment by thysultan** [comment]
Thanks, can you make a codesandbox with the mentioned `<input type="checkbox">`, `<input type="radio">`, `<select>` and `<textarea>` cases that DIO handles differently?

**Comment by rosenfeld** [comment]
As you can see here, only the `select` case is handled differently among React and Dio.js:

https://codesandbox.io/s/jnzk0pn3l5

**Comment by thysultan** [comment]
Is there a reason you used `defaultChecked` instead of `defaultValue` for `checkbox` and `radio`.

**Comment by rosenfeld** [comment]
Yes, I tried to copy the documentation in the comment above, but Github modified it, I'll try again escaping everything:

```
Likewise, <input type="checkbox"> and <input type="radio"> support defaultChecked,
 and <select> and <textarea> supports defaultValue.
```

**Comment by thysultan** [comment]
This looks like it would be nice to support. Something along the lines of pseudo code `if prop is defaultValue && value is not defined && type is select : use defaultValue as value"`.

**Comment by rosenfeld** [comment]
yes, I'm just curious how you're going to check if value is not defined in the DOM...

**Comment by rosenfeld** [comment]
the idea is that the value should be set only when the element is inserted in the DOM and left alone if the element was already rendered to the DOM.

**Comment by rosenfeld** [comment]
I haven't tested the behavior when defaultValue is changed in a separate render process, but I can't think of a valid use case where that would make sense. Have no idea how it works in React either. But what I meant with my previous comment is that your algorithm "value is not defined" can be tricky if you're talking about the DOM element value property as it wouldn't be undefined, right?

**Comment by rosenfeld** [comment]
I've just tested it and React won't touch the element's value unless it's re-rendered in the DOM (I think): https://codesandbox.io/s/oj2vpm40x5

**Comment by thysultan** [comment]
I was talking about the virtual props i.e in jsx syntax `<select value="a" defaultValue="b">` would indicate that value would take precedence over defaultValue.

**Comment by rosenfeld** [comment]
Yes, but the documentation talks about using `defaultValue` with uncontrolled components. When you set the value it's a controlled one, so defaultValue doesn't make sense I guess.

**Comment by rosenfeld** [comment]
I just tried it in CodeSandbox and value is used in that case

**Comment by thysultan** [comment]
I figure React does some kind of conditional like that to branch between controlled/un-controlled, so it would be identical in that respect.

**Comment by thysultan** [comment]
This is available with the release candidate for 9.0.0 [https://unpkg.com/dio.js@next](https://unpkg.com/dio.js@next)

**Comment by rosenfeld** [comment]
That's awesome, thanks!

**Comment by rosenfeld** [comment]
I'm facing an issue with dio.js 9 that I can't reproduce yet. Here's how the stacktrace looks like:

![image](https://user-images.githubusercontent.com/32246/38393556-8dd45fe2-3901-11e8-94c7-7bd4421c1450.png)

element.owner is returning an empty string ('') while dio.js is trying to remove that element from the parent node.

**Comment by rosenfeld** [comment]
After rolling back to the last release of dio.js I was able to actually see what was the actual error. After fixing the error I upgraded again to dio.js@next and it worked. It seems somehow Dio.js 9 is not handling errors in render() very well...

**Comment by thysultan** [comment]
I'm not sure i understood that, did you manage a reproduction?

**Comment by rosenfeld** [comment]
I can't reproduce in a sample application yet but I often get this error when there's a bug while rendering. I have to go back to Dio 8 in order to get the right stacktrace that allows me to understand the bug. The stacktrace is always like the one in the image above. You should probably check if element.children is actually an element before trying to remove it from its parent. For some reason it's an empty string sometimes.

**Comment by thysultan** [comment]
Do you have an error boundary preventing the error from propagating? 8.0 error boundaries did not work exactly like try..catch, they would always `console.error` the trace even when an error boundary caught it.

The error in the image looks like it is an empty DOM text node instead of an empty JavaScript string.

Though i still don't understand the problem yet, is any third party code removing elements from the DOM?

**Comment by rosenfeld** [comment]
Yes, I do have an error boundary, but it doesn't work when this error happens.

That's right, it' an empty text node.

There's no third party code (or my own) manipulating the DOM directly except for Dio.js. Well, actually sometimes I'd call someInput.value = '' but that's all DOM manipulation I do.

**Comment by thysultan** [comment]
That's ok, adding DOM nodes or mutating DOM props is always fine, it's only a problem when you remove a DOM node that the virtual DOM then tries to removes later that you might hit into an error like this. But that might not be the case here. 

Can you try removing the error boundary(comment out the componentDidCatch method), or if it's public share the related repository, that i could checkout and reproduce locally.

**Comment by rosenfeld** [comment]
I'm working on a quick-start project (a set of projects actually) which I intend to open-source once it's more polished, but if you have a Gitlab account I can give you access to it before-hand. Then I can explain it to you how to reproduce using it. Do you have a Gitlab account? What is it?

**Comment by thysultan** [comment]
Yes, [@thysultan](https://gitlab.com/thysultan)

**Comment by rosenfeld** [comment]
And so that you know in advance, it doesn't make any difference if I disable the ErrorBoundary component.

**Comment by rosenfeld** [comment]
Hi, I just added you to the project. Feel free to reach me at rr.rosas@gmail.com (it could be hangouts too if you prefer) for instructions on how to run it and reproduce the issue.

**Comment by thysultan** [comment]
The good news is i think i know what fixes that issue – In [https://github.com/thysultan/dio.js/blob/9.0.0/src/Core/Commit.js#L354](https://github.com/thysultan/dio.js/blob/9.0.0/src/Core/Commit.js#L354) adding an `if(element.active)` clause, prevents the error.

However i still don't know how to reproduce the issue outside of your setup.

**Comment by rosenfeld** [comment]
I'm glad I developed that starter project before writing the actual application :) Otherwise it seems it would be near to impossible to reproduce the issue without disclosing my actual application :) After all, you know your library, you could reproduce the issue and still don't know how to create a small sample application to demonstrate it :) Good luck :)

**Comment by rosenfeld** [comment]
Also, please take a look at yet another difference between Dio.js and React behavior when some state used for defaultValue is modified in-place in a non-constant function passed to the ref property (so that it's executed upon every render() call):

https://codesandbox.io/s/oj82jkw40y

**Comment by thysultan** [comment]
I think that is related to the current behavior of `defaultValue` updating after initial mount reported above as opposed to state semantics, that is to say trying this on a local version that has this fix mimics the commented React version.

**Comment by thysultan** [comment]
[9.0.0-rc0](https://unpkg.com/dio.js@next) fixes both issues mentioned here.

**Comment by rosenfeld** [comment]
Awesome, thanks!
