### ISSUE TITLE
State will not be updated if shouldComponentUpdate returns false

### ISSUE THREAD

**Issue by mcjazzyfunky** [thysultan/dio.js#57]
As this is the first issue I've opened for "dio.js" let my first thank @thysultan et al. for that really great DIO library.

#### Bug description:
Like the title already says, the method "setState" does not update "this.state" if the method "shouldComponentUpdate" returns false (DIO 8.x and 9.x).
This is working properly in React.

Demo:
https://jsfiddle.net/u4d4ufxv/

**Comment by thysultan** [comment]
Can this be a bug in React? The DIO version seems to work as expected, that is when the checkbox is checked, state is not updated in DIO though it is with React. What am i missing?

**Comment by js-works** [comment]
The problem is, that "setState" should ALWAYS update the state - but currently DIO's "setState" does NOT update the state if "shouldComponentUpdate" returns false.

**Comment by mcjazzyfunky** [comment]
The problem is, that "setState" should ALWAYS update the state - but currently DIO's "setState" does NOT update the state if "shouldComponentUpdate" returns false.

**Comment by thysultan** [comment]
Your right, i was under the impression that `shouldComponentUpdate` should also prevents state updates in React.

**Comment by thysultan** [comment]
Thanks for finding this, [9.0.1](https://github.com/thysultan/dio.js/releases/tag/9.0.1) patches this difference.

**Comment by mcjazzyfunky** [comment]
Hehe, that was really fast ;-)
Seems to work properly now.
Thanks a lot...
