### ISSUE TITLE
"forceUpdate" does not always update the view

### ISSUE THREAD

**Issue by mcjazzyfunky** [thysultan/dio.js#59]
#### Bug description (bug is to be found at least in V8.2.4 and V9.0.2):

There are rare cases where "forceUpdate" does not really update the view.
In those particular cases after calling "forceUpdate" the method "shouldComponentUpdate" is invoked before the intended view update, and if "shouldComponentUpdate" returns false then the view update will be cancelled.
The problem: After "forceUpdate" is called there should NOT be a "shouldComponentUpdate" check before rerendering, "forceUpdate" should ALWAYS update the view.

Those cases are quite exotic and a bit diffucult to explain - please check the component "DioCounterInfo" and "ReactCounterInfo" in the following demo to see what I mean:

https://jsfiddle.net/1q6whvye/

Please be aware that even if that use case seems really exotic and looks like kinda bad implementation, there are nevertheless real-world use cases where that bug matters - otherwise I would not have found it ;-)

**Comment by thysultan** [comment]
Yes, this is indeed strange, and makes for good test, i have a patch for this in the works.

**Comment by thysultan** [comment]
Patched in [9.0.3](https://github.com/thysultan/dio.js/releases/tag/9.0.3). Once again thanks for finding these subtle issues :)
