### ISSUE TITLE
create TypeScript type definition file for core and nano

### ISSUE THREAD

**Issue by thysultan** [thysultan/dio.js#6]

**Comment by thysultan** [comment]
@xenogenesi typescript definitions landed in 5.1.0

**Comment by xenogenesi** [comment]
@thysultan cool, I'll give a try in few hours

**Comment by xenogenesi** [comment]
@thysultan , I'm having some hard-time, perhaps due to my still limited ts knowledge, trying to extending `Props` to support some other attribute (`label`, `href` ...), what would be the proper way? 
In my `.ts` I tried declaring another `interface Props` and `interface MyProps extends Props` then extending `dio.Component<MyProps>` but either way are failing, I get errors from `h()` calls:

    error TS2345: Argument of type '{ href: string; onClick: any; }' is not assignable to parameter of type 'Props'.
      Object literal may only specify known properties, and 'href' does not exist in type 'Props'

`tsc` version is 2.1.4

**Comment by thysultan** [comment]
@xenogenesi Im also a novice with typescript myself. So i found that if 

```
interface Props {
    href?: string;
    label?: string;
}
```
doesn't work then dio.d.ts needs to have a `[custom: string]: any;` as one of the parameters to support any other key not defined there, i'll add a patch for this in a moment.

**Comment by xenogenesi** [comment]
@thysultan thanks, kinda liked having errors on wrong attributes, I'll look a bit more into it.

**Comment by thysultan** [comment]
@xenogenesi post your findings if you find anything, would prefer that as well.

**Comment by xenogenesi** [comment]
So, the problem wasn't extending the interface, `interface MyProps extends Props` and `class MyClass extends dio.Component<MyProps>` are working, I just needed to add a declaration for `h()` with a signature for `MyProps`

    declare function h(type: Type, props?: MyProps, ...children: Array<any>): VNode;

Sorry for wasting your time and thanks.

**Comment by thysultan** [comment]
@xenogenesi actually If `Type` and `VNode` is exposed then 

```
interface Props {
	href?: string;
        // ...
}
```
should work, it works for me, but i'm using `/// <reference path="../dio.d.ts" />` can you confirm?

**Comment by xenogenesi** [comment]
I'm using `///<reference path="../node_modules/dio.js/dio.d.ts" />`, using `interface Props {` only (as I also read it should work) doesn't work, and I get errors as mentioned above about unknown properties.
