### ISSUE TITLE
support error boundaries?

### ISSUE THREAD

**Issue by thysultan** [thysultan/dio.js#7]
inspired by fiber, dio v5.2.0 might introduce error boundaries, this issue will document possible implementation details.

```js
class Foo extends dio.Component {
    componentDidThrow (err) {
        switch (err.location) {
            case 'componentDidMount': return h('h1', 'something bad happened in did mount');
            case 'render': return h('h1', 'something bad happened in render');
        }
    }
    componentDidMount () {
       throw 'pawned!';
    }
    render () {
        return h('h1', 'Hello World');
    }
}
```

After componentDidMount throws, it will first render nothing from the Foo component and continue to the end of the stack at which point it will then re-try to render the Foo component, if it still fails it will then capture the error and pass it to `componentDidThrow` if it exists, if `componentDidThrow` returns something that can render(element/string/array) dio will render that else continue to render nothing. If `componentDidThrow` is not defined it fallbacks to the default error handler that prints a `console.error` of the error and continues to render nothing.

```
Dio caught an error thrown by "Foo", the error was thrown in "componentDidMount".
```

The object passed to `componentDidThrow` will have the shape

```
{
    from: 'Foo',
    location: 'componentDidMount',
    message: 'pawned!',
    stack: 'js stack trace...'
}
```

`render`, lifecycle methods and callbacks passed to `setState` and `forceUpdate` will fall within the areas that are supported by error boundaries.

**Comment by lukeed** [comment]
Interesting. Would this be development only?

**Comment by thysultan** [comment]
@lukeed both development and production since it's more useful in production in reducing single points of failure that could take down a whole app.
