### ISSUE TITLE
v7.0.0 [new features]

### ISSUE THREAD

**Issue by thysultan** [thysultan/dio.js#9]
v7.0.0 is a new version that will come out soon, this issue acts as a issue tracking on the progress including changes and new features that will come with it.

### new features

1. First class support for lazy loading components and stylesheets.
2. Adds `dio.fetch` top level API
3. Adds `progress` to http API `dio.fetch('', {progress: (e) => {}})`) 
4. Adds `dio.module` top level API.
5. Improves coroutine components `done` rendering state.
6. Removal of `dio.request(options)`, in favour of `fetch(url, options)`

### breaking changes

V7.0 will introduce a few breaking changes if something other than the high level api's `createElement` or `h` are being used to create virtual element this includes `createFactory` but excluding `DOM`, other than that nothing else should break.

## 1. Lazy Loading Components

First class support for lazy loading components will allow for the following asynchronous component loading pattens.

```scss
// Components/Bar/index.css 
& {
	color: red;
}
```

```js
// Components/Bar/index.js
class Bar extends Component {
	render ({message}) {
		return h('h1', message);
	}
}

export default Bar;
```

```js
// entry.js
const {fetch, Component} = dio;

class Slot extends Component {
	stylesheet () {
		return fetch('Components/Bar/index.css');
	}
	render () {
		return fetch('Components/Bar/index.js', {
                        body: {message: 'Hello World'},
			progress: h('h1', 'Loading Component...')
		})
	}
}

dio.render(Slot);
```

When render is called Slot progress element `<h1>Loading Component</h1>` will mount. After the `index.js` file is loaded into the browsers VM and the exported component in `index.js` replaces the progress element on the other hand `index.css` is loaded, name-spaced and added to the page. If a function is passed as opposed to a virtual element as the value of a property `progress` on the optional second argument of `fetch()` will expose the `ProgressEvent` object as a single argument.

## 2. Fetch

`dio.fetch` will mimic for the most part the window.fetch, the introduction of this API also introduces context aware request that makes returning a http request object from an render method.

## 3. Fetch/Request progress

```js
fetch('foo.js', {
    progress: ({loaded, total, timeStamp}) => {
        console.log(total - loaded, timeStamp);
    }
})
```

## 4. Modules

`dio.module` is the low-level module loader that `fetch` uses when returned from a render method.

```
// entry.js
module('foo.js').then((foo) => {
    foo.add(1, 2);
})

// foo.js
const add = (a, b) => a + b;
export {add}
```

If you wanted to transpile modules on the fly before consumption `dio.module` also allows you to register one via `dio.module.transpile = fn`

## 5. Improve Coroutines "done" state

This may be a feature or bug depending on how it's view but currently when a coroutines component reaches a `done` state it is unmounted on the next render. v7.0.0 will change this behavior to prevent unmounting when `done` and the subsequent `.next()` returns nothing.

**Comment by flagello** [comment]
Congrats on the release @thysultan!

**Comment by thysultan** [comment]
@flagello Thanks
